version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasksdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./packages/backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/tasksdb
      GOOGLE_GEMINI_API_KEY: ${GOOGLE_GEMINI_API_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
    ports:
      - '3001:3000'
    depends_on:
      - db
    command: ["npm", "start"]

volumes:
  pgdata: 